apiVersion: app/v1
kind: Replicaset
metadata: 
  name: my-app-replicaset
  labels:
    app: myapp 
spec: 
  selector: 
    matchLabels:
      app: myapp 
  replicas: 3
  template:
    metadata: 
      name: nginx-2
      labels:
        app: myapp 
    spec:
      containers: 
        - name: nginx
          image: nginx